# Generated by Django 4.2.11 on 2026-04-17 03:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('satellite_image', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('start_lat', models.FloatField(blank=True, null=True)),
                ('start_lon', models.FloatField(blank=True, null=True)),
                ('end_lat', models.FloatField(blank=True, null=True)),
                ('end_lon', models.FloatField(blank=True, null=True)),
                ('green_pct', models.FloatField(default=0)),
                ('dust_pct', models.FloatField(default=0)),
                ('builtup_pct', models.FloatField(default=0)),
                ('shade_pct', models.FloatField(default=0)),
                ('congestion_pct', models.FloatField(default=0)),
                ('water_pct', models.FloatField(default=0)),
                ('ndvi', models.FloatField(blank=True, null=True)),
                ('ndbi', models.FloatField(blank=True, null=True)),
                ('comfort_score', models.FloatField(default=0)),
                ('risk_category', models.CharField(choices=[('safe', 'Safe'), ('moderate', 'Moderate'), ('risky', 'Risky')], default='moderate', max_length=20)),
                ('aqi', models.FloatField(blank=True, null=True)),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('pm10', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_cached', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='dashboard.city')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
