# Generated by Django 4.2.11 on 2026-04-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='dl_available',
            field=models.BooleanField(default=False),
        ),
    ]
