# Generated by Django 4.2.11 on 2026-04-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_analysisresult_dl_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='image_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='image_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
